version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python ensure_database.py &&
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:



