"""change task model

Revision ID: b36ac2e23349
Revises: c19292b3bee8
Create Date: 2025-09-03 19:46:19.819443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = 'b36ac2e23349'
down_revision: Union[str, Sequence[str], None] = 'c19292b3bee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), server_default='pendiente', nullable=False))

    op.execute(
        "UPDATE tasks SET created_at = NOW() WHERE created_at IS NULL"
    )

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               nullable=False,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
